name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true 

      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v13
        with:
          name: rdk31-dotfiles
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix build -L .#nixosConfigurations.xps-ci.config.system.build.toplevel

      - run: nix flake check
