name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: rdk31-dotfiles
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build
        run: nix build -L .#nixosConfigurations.xps.config.system.build.toplevel
      - name: Cache
        if: github.ref == 'refs/heads/master'
        run: cachix push rdk31-dotfiles ./result
