name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo rm -rf /opt&
      - run: sudo rm -rf /usr/share/dotnet&
      - run: sudo rm -rf "/usr/local/share/boost"&
      - run: sudo rm -rf "$AGENT_TOOLSDIRECTORY"&

      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: rdk31-dotfiles
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix build -L .#nixosConfigurations.xps.config.system.build.toplevel

      - run: nix flake check
